### ISSUE TITLE
enhancement : add theme=small

### ISSUE THREAD

**Issue by KrifaYounes** [vaadin/vaadin-combo-box-flow#110]
theme=small is not working on vaadin-combo-box
<vaadin-combo-box id="bankActionType" theme="small" class="cell" label="Type" readonly ></vaadin-combo-box>
it's working only for vaadin-text-field

enhancement : add theme=small for vaadin-combo-box

**Comment by pekam** [comment]
Hi!

This repository is only for the Java integration of the `<vaadin-combo-box>` web component.

This feature would be implemented in the web component, so you probably want to make the feature request to https://github.com/vaadin/vaadin-combo-box
