### ISSUE TITLE
Rendering items using ComponentTemplateRenderer" should tell what the demo is about

### ISSUE THREAD

**Issue by mickoyuh** [vaadin/vaadin-combo-box-flow#112]
Moved from website Gitlab. Reported by Artur. 
--
https://vaadin.com/elements/vaadin-combo-box/java-examples/using-components

ComponentTemplateRenderer is probably some concept core Flow developers are familiar with but a web site visitor wants to know what heshe can accomplish.

**Comment by web-padawan** [comment]
The demo linked above has been removed. Here are the new demos:
https://vaadin.com/components/vaadin-combo-box/java-examples/presentation

- Customizing drop down items with ComponentRenderer
- Customizing drop down items with TemplateRenderer

I hope those are self-descriptive enough. If not, please create a new issue.
