### ISSUE TITLE
1.0.5 release has incorrect parent dependency version

### ISSUE THREAD

**Issue by lightoze** [vaadin/vaadin-combo-box-flow#115]
Maven Central release POM has com.vaadin:flow-component-base:pom:1.0-SNAPSHOT as a parent, which cannot be resolved.
https://search.maven.org/artifact/com.vaadin/vaadin-combo-box-flow/1.0.5/jar

**Comment by lightoze** [comment]
Upd: vaadin-grid-flow:1.0.4 has the same problem, other components for platform 10.0.3 release are OK.

**Comment by denis-anisimov** [comment]
Well, thank you for reporting but we can't do anything already with the released versions.
Though it's quite weird.

Anyway, there is already a new version released and it has the correct versions:

http://central.maven.org/maven2/com/vaadin/vaadin-combo-box-flow/1.0.6/vaadin-combo-box-flow-1.0.6.pom

http://central.maven.org/maven2/com/vaadin/vaadin-grid-flow/1.0.5/vaadin-grid-flow-1.0.5.pom
