### ISSUE TITLE
Placeholder when no items are returned from lazy data provider

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-combo-box-flow#142]
When no items are returned from a lazy data provider (e.g. too restrictive filter), the dropdown is squeezed and empty: this differs from what happens with a fixed set of items, i.e. no dropdown is displayed (instead of an empty one); plus, there is no feedback during server-side filtering.

What about a placeholder item like "Searching..." during the server round-trip and something like "No items found" when the server returns zero items?

**Comment by Legioth** [comment]
One thing to notice is that messages such as  "Searching..." would also have to be translatable.

**Comment by pekam** [comment]
A spinner icon will be added to the web component. It will replace the down-arrow while the component is waiting for data to be fetched.

**Comment by pekam** [comment]
Actually the design seems to be still in progress. It might be that the spinner will be located in the overlay. Anyway this is the issue for it: https://github.com/vaadin/vaadin-combo-box/issues/710
