### ISSUE TITLE
clearing an empty combobox leads to nullpointer

### ISSUE THREAD

**Issue by JonasManuelKonstruktum** [vaadin/vaadin-combo-box-flow#148]
Observed behavior:
In v 2.0.0.alpha1 , calling clear() on an empty combobox leads to a nullpointer exception on the datacommunicator.

My Expectation:
Clearing an empty box does nothing.

**Comment by pekam** [comment]
We had similar issue #146, which I resolved by just throwing a more meaningful exception, as setting a value doesn't make sense for a ComboBox without items to select.

This is kind of the same thing, as `clear()` is just a convenience method for `setValue(null)`.

I can of course fix this case, but out of curiosity, what is the use-case of having a ComboBox without items/dataprovider and even calling `clear()` on it?

**Comment by pekam** [comment]
Ok, makes sense now. I pushed a fix for it: #150 
Thanks for using the pre-release and providing feedback!
