### ISSUE TITLE
vaadin-combo-box-flow 4.2.0  not available in maven repo

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-combo-box-flow#157]
_From @KrifaYounes on November 28, 2018 11:17_

vaadin-combo-box-flow 4.2.0 is not available in maven repository
https://maven.vaadin.com/vaadin-prereleases/com/vaadin/vaadin-combo-box-flow/

_Copied from original issue: vaadin/vaadin-combo-box#749_

**Comment by mehdi-vaadin** [comment]
The latest version of `vaadin-combo-box-flow` at the moment is `2.0.0`.
