### ISSUE TITLE
error with version 2.0.0 

### ISSUE THREAD

**Issue by KrifaYounes** [vaadin/vaadin-combo-box-flow#158]
I got this error : combobox.clearcache  is not a function when I installed this dependency

 ```
  <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-combo-box-flow</artifactId>
            <version>2.0.0</version>
  </dependency>
```

```
Uncaught TypeError: comboBox.clearCache is not a function
    at Object.comboBox.$connector.reset (comboBoxConnector.js:117)
    at Object.eval (eval at jt (client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:972), <anonymous>:3:15)
```

**Comment by mehdi-vaadin** [comment]
@KrifaYounes I couldn't reproduce this bug. Would you please share a piece of code that causes this error? Which version of Vaadin are you using?

**Comment by KrifaYounes** [comment]
@mehdi-vaadin I use vaadin 11.0.1 and I reproduce with vaadin 11.0.2

**Comment by mehdi-vaadin** [comment]
I can't still reproduce this error. You should provide a simple project where you can see this error.

**Comment by pekam** [comment]
Sounds like you have incompatible versions of `vaadin-combo-box-flow` and `vaadin-combo-box` web component.

`vaadin-combo-box-flow` 2.0 is compatible with `vaadin-combo-box` 4.2

Something in your project setup is overriding the web component version to an older one.
