### ISSUE TITLE
setItems does not update the size

### ISSUE THREAD

**Issue by Fr33z3m4n** [vaadin/vaadin-combo-box-flow#159]
after setItems is called again, the size in the combobox is not updated.

Example: (ComboBoxPage.java - Test)

```
private void createWithUpdateProvider() {
        ComboBox<String> comboBox = new ComboBox<>();

        comboBox.setItems("foo", "bar", "test", "test 2", "test 3");
        comboBox.setId("combo");

        NativeButton setProvider = new NativeButton("Update data provider",
                event -> comboBox.setDataProvider(
                        DataProvider.ofItems("baz", "foobar")));
        setProvider.setId("update-provider");

        NativeButton setItemCaptionGenerator = new NativeButton(
                "Update caption generator",
                event -> comboBox.setItemLabelGenerator(
                        item -> String.valueOf(item.length())));
        setItemCaptionGenerator.setId("update-caption-gen");

        NativeButton setValue = new NativeButton("Update value",
                event -> comboBox.setValue("baz"));
        setValue.setId("update-value");

        add(comboBox, setProvider, setItemCaptionGenerator, setValue);
    }
```

1. 
![grafik](https://user-images.githubusercontent.com/1181557/49217462-e45dd500-f3cd-11e8-9f0e-89f718e82bb6.png)

2. After Update
![grafik](https://user-images.githubusercontent.com/1181557/49217479-f475b480-f3cd-11e8-9a3f-5fb0e89e09a3.png)

**Comment by Fr33z3m4n** [comment]
Workaround: Update setPageSize and setSize

@Override
public void setDataProvider(ListDataProvider<T> listDataProvider) {
	if (listDataProvider.getItems().size() > 0)
		setPageSize(listDataProvider.getItems().size());
	setSize(listDataProvider.getItems().size());
	super.setDataProvider(listDataProvider);
}

**Comment by pekam** [comment]
This was a bug in the web component, and the issue will be closed once the integration test is merged.

See comment in the duplicate ticket: https://github.com/vaadin/vaadin-combo-box-flow/issues/177#issuecomment-462396562
