### ISSUE TITLE
addCustomValueSetListener is fired twice on adding new item

### ISSUE THREAD

**Issue by anasmi** [vaadin/vaadin-combo-box-flow#167]
Vaadin version : 12.0.1

Worked in 11.0.3

Code to reproduce : 
```
        final ComboBox<String> combobox = new ComboBox<>("Farbauswahl");
        ArrayList<String> items=new ArrayList<>(Arrays.asList("rot", "grün", "gelb", "blau"));
        combobox.setItems(items);
        combobox.addCustomValueSetListener(event->{
            items.add(event.getDetail());
            combobox.setItems(items);
            combobox.setValue(event.getDetail());
        });

        Button button = new Button("Click me",
                event -> Notification.show("Clicked!" + combobox.getValue()));
        combobox.setAllowCustomValue(true);
        add(combobox);
        add(button);
```

- Listener is called twice-->element is added twice to the list. Both are selected at the same time. 

- Trying  to add element (blurring by clicking on the button) and click event is not fired, but the screen "jumps"

- Trying to verify if the component already exist in the list doesn't solve the issue much. (Selection is dropped on closing/opening popup)

**Comment by pekam** [comment]
The issue was in the web component side. Will be fixed by https://github.com/vaadin/vaadin-combo-box/pull/799
