### ISSUE TITLE
calling setItems causes a client-side exception

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/vaadin-combo-box-flow#169]
`vaadin.version 12.0.1`
Setting the items to a previously-uninitialized ComboBox causes a client-side exception.
Simple demo that reproduces the issue:

```
public class MainView extends VerticalLayout {

    public MainView() {
        ComboBox<String> comboBox = new ComboBox<>();
        Button button = new Button("Click me to add items to the combobox",
                event -> comboBox.setItems("foo", "bar"));
        add(comboBox, button);
    }
}
```
Clicking the button causes a bunch of TypeErrors on the client side:
```
client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:197 (TypeError) : Cannot read property 'reset' of undefined
```
Workaround is to initialize the ComboBox with an empty Collection.

**Comment by Silver-Wulf** [comment]
Is the intended functionality of this to have the ComboBox allow for setItems to work normally even if it is not yet initialized with a collection?
