### ISSUE TITLE
Using setAutoFocus() makes the first keystroke not to filter items

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/vaadin-combo-box-flow#171]
Tested on Vaadin Platform Version: 12.0.2
If I create a normal combobox and use the method `setAutoFocus()` and start the application, if I press a key that is present in some items, it will show all of the items without filtering. It also happens when I use the method `focus()`.
If I do not use those methods, if I first click on the combo and then press the same key, it will work as expected, filtering the items.
Here's an animated gif showing the problem:

![comboboxissue1](https://user-images.githubusercontent.com/28312758/50017159-1e240380-ffaa-11e8-9f28-5747e504574e.gif)

Here's the code of that sample application:

```@Route("")
@PWA(name = "Project Base for Vaadin Flow", shortName = "Project Base")
public class MainView extends VerticalLayout {

	 public MainView() {
	
		 ComboBox<String> cb = new ComboBox<>("Choose option","Option 2","Option 3","Option 4","Option 5");
		 this.add(cb);
		 cb.focus();
	
	 }

}

**Comment by bogdanudrescu** [comment]
Related to #172 and fixed by https://github.com/vaadin/vaadin-combo-box-flow/pull/191
