### ISSUE TITLE
Using setAutoFocus() and custom DataProvider creates empty item labels when filtering

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/vaadin-combo-box-flow#172]
Tested on Vaadin Platform Version: 12.0.2
If I create a combobox and use the method `setAutoFocus()`, provide a custom data provider with filtering and start the application, if I press a key that is present in some items, it will show the filtered list, but without the text of each item.
If I do not use `setAutoFocus()`, if I first click on the combo and then press the same key, it will work as expected, filtering the items and showing the labels.
Here's an animated gif showing the problem:

![comboboxissue2](https://user-images.githubusercontent.com/28312758/50017517-1153df80-ffab-11e8-9834-83971c87be04.gif)

Here's the code for that sample application:

```
@Route("")
@PWA(name = "Project Base for Vaadin Flow", shortName = "Project Base")
public class MainView extends VerticalLayout {

	public MainView() {
		List<String> data = Arrays.asList("Option 2", "Option 3", "Option 4", "Option 5", "Another Option 2");

		ComboBox<String> cv = new ComboBox<>("Choose option");
		cv.setDataProvider((ComboBox.FetchItemsCallback<String>) (filter, offset, limit) -> {
			if (filter.isEmpty())
				return Stream.of("");
			return data.stream().filter(s -> s.contains(filter)).skip(offset).limit(limit);
		}, (filter) -> {
			if (filter.isEmpty())
				return 1;
			return (int) data.stream().filter(s -> s.contains(filter)).count();
		});

		cv.setAutofocus(true);
		this.add(cv);

	}

}
```

**Comment by bogdanudrescu** [comment]
Duplicate of #171
