### ISSUE TITLE
Using both a validator and asRequired on a combo box results in the asRequired flag supressing validation errors

### ISSUE THREAD

**Issue by brp-benjamin** [vaadin/vaadin-combo-box-flow#179]
Binding a combo box with a custom validator as well as making the field required will surpress validation errors from the custom validator.

An implementation that demonstrates this can be found at:
https://github.com/brp-benjamin/skeleton-starter-flow/tree/combobox-validator-and-required-error

See the following screenshot as a demonstration of the error
![bild](https://user-images.githubusercontent.com/42134286/50223703-42ae2000-039c-11e9-9c8b-9dd5277a7727.png)

**Comment by denis-anisimov** [comment]
Thanks a lot for exact steps to reproduce.

This is a bug.
`asRequired`  uses `setRequiredIndicatorVisible` method which by default sets `required` property.
This property enables the client side validation which is inconsistent with the server side validation.
`TextField` has a special code which turns off the client side validation in case `setRequiredIndicatorVisible`  is called.
And the contract of `setRequiredIndicatorVisible`  explicitly mentions that this method should disable the client side validation.
