### ISSUE TITLE
Setting value to null displays a number in ComboBox

### ISSUE THREAD

**Issue by mstahv** [vaadin/vaadin-combo-box-flow#180]
If custom values are enabled, setting value to null in value change listener causes ComboBox displays a number as value.

A code to reproduce (tested with 12.0.3, but I think the issue has been there always):

    public static class Person implements Serializable {
        private String name;
        public Person(String firstName) {
            this.name = firstName;
        }
        @Override
        public String toString() {
            return name;
        }
    }

    public MainView() {
        Person jorma = new Person("Jorma");
        Person kalle = new Person("Kalle");
        List<Person> list = Arrays.asList(jorma, kalle);

        ComboBox<Person> cb = new ComboBox<>();
        cb.setItems(list);
        cb.addValueChangeListener(e -> {
            e.getSource().setValue(null);
        });

        cb.setAllowCustomValue(true);
        add(cb); // MainView extends VerticalLayout
    }

In above MainView, just choose "Jorma" -> ComboBox shows 1, even though it should be empty.

Client side console shows this message:

    Warning: unable to determine the label for the provided `value`. Nothing to display in the text field. This usually happens when setting an initial `value` before any items are returned from the `dataProvider` callback. Consider setting `selectedItem` instead of `value`

**Comment by WoozyG** [comment]
"always" appears to be ">=V10" as I can't reproduce this in Vaadin 8.  That might help narrow it down.

**Comment by Silver-Wulf** [comment]
What is the intended functionality of setValue when null is used?

**Comment by mstahv** [comment]
The value should be undefined, it should be cleared. If there is no "placeholder" set, the textbox should be empty, otherwise it should show the placeholder.

**Comment by Silver-Wulf** [comment]
The pull request I made should fix your issue @mstahv. The number being displayed is a totally different issue that I will make an issue for and link back to this one.

**Comment by bogdanudrescu** [comment]
This looks like an issue in the webcomponent itself, although we may workaround it in flow.

**Comment by mstahv** [comment]
As a Flow user I wouldn't really care if there is a workaround, I just care about random numbers appearing on my person list. This issue is blocking my first Vaadin 10+ application (migrated from V6) to become "production quality". There are still lot of other issues, but those can be somehow worked around, for this I have no sane way.

**Comment by Silver-Wulf** [comment]
@mstahv #186 demonstrates a work-around that will help you for now. Issue #187 details the second bug that causes the appearances of the numbers which does not occur when using the fix in #186, if you want more details on the issue at hand.
