### ISSUE TITLE
OSGi: ERROR: bundle com.vaadin.flow.component.combobox:2.0.1 (75)Component descriptor entry 'OSGI-INF/com.vaadin.flow.component.combobox.osgi.ComboBoxConnectorResource.xml' not found

### ISSUE THREAD

**Issue by enver-haase** [vaadin/vaadin-combo-box-flow#193]
ERROR: bundle com.vaadin.flow.component.combobox:2.0.1 (75)Component descriptor entry 'OSGI-INF/com.vaadin.flow.component.combobox.osgi.ComboBoxConnectorResource.xml' not found

when starting up the base-starter-flow-osgi

**Comment by pleku** [comment]
Fixed with https://github.com/vaadin/flow-component-base/issues/116 since 12.0.3
