### ISSUE TITLE
clearing a custom value does not invoke any listeners

### ISSUE THREAD

**Issue by bbaumgartner** [vaadin/vaadin-combo-box-flow#197]
Vaadin flow 12.0.4

Given:

        combo = new ComboBox<>();
        combo.setLabel(getLabel());

        combo.setPreventInvalidInput(false);
        combo.setAllowCustomValue(true);

        combo.addValueChangeListener(event -> {
            onSuggestionSelection(event.getValue());
            setValue(event.getValue() == null ? null : event.getValue().getValue());
        });
        combo.addCustomValueSetListener(event -> setValue(event.getDetail()));

1. Selecting a value from the drop down results in call to ValueChangeListener
2. Invoking the clear action (the little X button in the text field) results in call to ValueChangeListener
3. Entering a value not in the drop down list results in a call to CustomValueSetListener
4. Invoking the clear action results in no call to any listener

This is a problem because the server side does not know that the field has being cleared by the user.

Regards
Benno

**Comment by bbaumgartner** [comment]
Actually this is also the case when deleting the custom value without the X action.

**Comment by pekam** [comment]
If you are not explicitly setting value for the combo box on custom-value-set events (I can't know what your `setValue` method in the example does), then everything works as expected:
- initially combo box's value is `null`
- enter a custom value
  - `CustomValueSetEvent` is fired
  - combo box's value is still `null`
- clear the value
  - value is still `null` -> no `ValueChangeEvent`
  - not setting a custom value -> no `CustomValueSetEvent`

See related discussion in #237.
Also, some fixes have been done to the custom-value feature, and it should work properly in V14.
