### ISSUE TITLE
ComboBox initialized with ListDataProvider still shows lazy spinner

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/vaadin-combo-box-flow#199]
`<vaadin.version>12.0.5</vaadin.version>`
ComboBox initialized with a ListDataProvider without a filter should do the filtering on the client side. However, it seems that there are still network requests (and the spinner is showing) even if I use the `setDataProvider(ListDataProvider<T> listDataProvider)` method to initialize the ComboBox:
```
        ListDataProvider<String> ldp = new ListDataProvider<>(IntStream.range(0, 100).
                mapToObj(number -> "Item: " + number).
                collect(Collectors.toList()));
        ComboBox<String> myComboBox = new ComboBox<>("Combo");
        myComboBox.setDataProvider(ldp);
```

**Comment by Legioth** [comment]
> ComboBox initialized with a ListDataProvider without a filter should do the filtering on the client side.

Is this something this something implied by documentation, or is it something that you expect based on other circumstances?

In cases with shared in-memory data, e.g. a global list of hardcoded alternatives, there's nothing that prevents having thousands of items in a `ListDataProvider`, but it would not be appropriate to send all of them up-front to the client.

**Comment by OlliTietavainenVaadin** [comment]
see https://github.com/vaadin/vaadin-combo-box-flow/issues/201

**Comment by pekam** [comment]
It works as designed: Filtering happens in client side iff
`dataSize < pageSize && !customServerSideFilterSetByUser`
The data provider type doesn't make a difference.

So I'd like to close this issue, unless you want argue that the behavior should be changed, @OlliTietavainenVaadin?

**Comment by OlliTietavainenVaadin** [comment]
Agreed, closing
