### ISSUE TITLE
Connector error with 2.1.1

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-combo-box-flow#219]
After upgrading to 13.0.0.beta2 (which brings 2.1.1) I get this client error from the connector:

```
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately.
(TypeError) : Cannot read property 'input' of undefined
The error has occurred in the JS code: '$0, $1, $0.$connector.enableClientValidation($1)'
```

Not sure what changed, but the same exact code worked before.

**Comment by heruan** [comment]
Cannot replicate anymore, so I'm closing for now; I'll reopen in case I confirm this.

**Comment by heruan** [comment]
This is indeed happening with 2.1.1 but only under these conditions:

1. the component which contains the `ComboBox` is a `PolymerTemplate`
2. the component which contains the `ComboBox` has at least an `@Id` field;
3. the `ComboBox` should at least have an `asRequired()` binding.

For example:

```html
<link rel="import" href="../bower_components/vaadin-tabs/vaadin-tabs.html">

<dom-module id="combo-test">
  <template>
    <div id="navigation" part="navigation">
      <vaadin-tabs id="tabs"></vaadin-tabs>
    </div>
    <div id="content" part="content">
      <slot></slot>
    </div>

  </template>

  <script>
    class ComboTest extends Polymer.Element {
      static get is() { return 'combo-test'; }
      static get properties() {
        return {
        };
      }
    }

    window.customElements.define(ComboTest.is, ComboTest);
  </script>
</dom-module>
```

```java
@Tag("combo-test")
@HtmlImport("combo-test.html")
public class ComboTest extends PolymerTemplate<TemplateModel> implements HasComponents {

    @Id("tabs")
    protected Tabs tabs;

    public ComboTest() {
        var cb = new ComboBox<String>();
        cb.setItems("Foo", "Bar");
        var binder = new Binder<Bean>();
        binder.forField(cb).asRequired().bind(Bean::getter, Bean::setter);
        this.add(cb);
    }

    interface Bean { String getter(); void setter(String value); }
}
```

**Comment by heruan** [comment]
Might have been caused by https://github.com/vaadin/vaadin-combo-box-flow/pull/202

**Comment by heruan** [comment]
This code replicates the connector error: [ComboTest.java](https://github.com/heruan/vaadin-spring-demo/blob/d1dbfff6b577f8dee2ccd35d67ad9042dcab161e/src/main/java/to/lova/vaadin/spring/ComboTest.java)

**Comment by heruan** [comment]
A similar issue that might be related having a common root cause is https://github.com/vaadin/vaadin-grid-flow/issues/515: in [this comment](https://github.com/vaadin/vaadin-grid-flow/pull/517#issuecomment-467092079) similar conditions are identified to likely cause a client error:

- being a `PolymerTemplate`
- having an `@Id` field

Both issues don't happen in 13.0.0.beta1, but only in 13.0.0.beta2.

**Comment by heruan** [comment]
I see this is being fixed and that's great, thank you! What was causing this? In 13.0.0.beta1 it worked.

**Comment by denis-anisimov** [comment]
You were right, it's a regression introduced by me via https://github.com/vaadin/vaadin-combo-box-flow/pull/202.

I've added a check for presence an element in the shadow root but forgot that the shadow root itself may be not yet available. Quite stupid and easy thing.

And thanks a lot for the exact code which reproduce the issue.

**Comment by heruan** [comment]
Thank you @denis-anisimov! Too bad it didn't make for V13 😢

**Comment by denis-anisimov** [comment]
Yeah, but you can just set direct dependency to the component `2.1.2` . Though this is an extra action.

**Comment by lucastanzani** [comment]
Hello.
I still get this error with 2.1.2 and 13.0.1:
When calling readBean on a previously empty combobox, and the binder has the asRequired property set. 
I noticed this too:
https://github.com/vaadin/flow/issues/5082
I don't know if it's the same or not
