### ISSUE TITLE
Items not rendered partially after scrolling in large combobox

### ISSUE THREAD

**Issue by steffen-harbich-itc** [vaadin/vaadin-combo-box-flow#227]
Have a look at my example based on starter project: 
[demo-combobox-items-not-rendered.zip](https://github.com/vaadin/vaadin-combo-box-flow/files/2937939/demo-combobox-items-not-rendered.zip)

The combobox has a lot of items. When scrolling down and up, some items are not rendered correctly anymore, though they still exist and can be selected:
![demo-combobox-items-not-rendered](https://user-images.githubusercontent.com/19586082/53907676-f646b800-404d-11e9-85d0-ee943aa83336.gif)

Same behavior in Vaadin 12.0.7 and 13.0.0.

**Comment by denis-anisimov** [comment]
Confirmed.

**Comment by pekam** [comment]
Seems to happen only when using `ComponentRenderer`. At least I couldn't reproduce with value providers or templates.
