### ISSUE TITLE
Lazy loading ComboBox in a Dialog fails to load the first batch of items when the Dialog is opened multiple times

### ISSUE THREAD

**Issue by kalmancsaba** [vaadin/vaadin-combo-box-flow#239]
I created a Dialog with a complex form. I used ComboBoxes with backend DataProvider. I tried to resue the Dialog by opening it multiple times subsequently (with different data object bound to the Binder). Everithing is fine, except the ComboBoxes don't load the first batch of items if the dialog is opened two or more times. 
I'm using Vaadin 13.0.1 (vaadin-combo-box-flow-2.1.2)

Minimal code to reproduce:

```
@Route("ComboBoxDialogTest")
public class ComboBoxDialogTest extends Composite<VerticalLayout> {

	public ComboBoxDialogTest() {
		ComboBox<String> cb = new ComboBox<>();
		cb.setDataProvider((filter, offset, limit) -> IntStream.range(offset, offset + limit)
			.mapToObj(i -> "Item " + i),
			filter -> 500);
		Dialog dialog = new Dialog(cb);

		Button btn = new Button("Open dialog");
		btn.addClickListener(evt -> dialog.open());

		getContent().add(btn);
		getContent().setSizeFull();
		getContent().setHorizontalComponentAlignment(Alignment.CENTER, btn);
		getContent().setJustifyContentMode(JustifyContentMode.CENTER);
	}
}
```

In the above example when first opening the Dialog, everything is fine. In subsequent Dialog opens the first 50 item of the ComboBox will not load, as shown below:

![combobox-in-dialog](https://user-images.githubusercontent.com/48769837/54775136-98999a80-4c0d-11e9-8c7e-dec23add4426.gif)

I know, there's an easy workaround by creating dialog content each time a dialog needs to be shown, but some of our dialogs are quite complex and need quite a few seconds to load. I would prefer pre-assembling the content and reuse it.

**Comment by pekam** [comment]
Hi!
It seems that this bug got fixed in vaadin-combo-box-flow 2.1.3, so I'm closing the issue.
