### ISSUE TITLE
Infinite loading when clearing the list of items

### ISSUE THREAD

**Issue by envoy93** [vaadin/vaadin-combo-box-flow#263]
I can not correctly clear the list of items if there were some values before. 
I use Vaadin 13.0.7
Please check a small example showing my issue:
```
        ArrayList<String> items = new ArrayList<>();
        ComboBox<String> comboBox = new ComboBox<>();
        comboBox.setItems(items);

        Button zero = new Button("Clear ALL", VaadinIcon.DEL.create(), event -> {
            items.clear();
            comboBox.getDataProvider().refreshAll();
            Notification.show("Items: " + items.size());
        });

        Button add = new Button("Add item", VaadinIcon.FILE_ADD.create(),event -> {
            items.add("Item");
            comboBox.getDataProvider().refreshAll();
            Notification.show("Items: " + items.size());
        });

        add(zero, add, comboBox); 
```

![clear_items](https://user-images.githubusercontent.com/3830719/57931144-e0b10280-78c8-11e9-824e-402c052726a4.gif)

Is this the correct behavior?

**Comment by pekam** [comment]
Bug verified. Setting an empty data set initially works fine, but if the combo box had items previously, the issue occurs.

This issue has been added to our backlog. Thanks for reporting!
