### ISSUE TITLE
Inconsistent behavior when using addCustomValueSetListener

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/vaadin-combo-box-flow#269]
With `14.0.0.beta2` and following code example on `project-base`

we can see different behavior with adding a new item

**case 1:** 
- add a new item 
![combobox-new-item2](https://user-images.githubusercontent.com/31067185/58417580-e3141900-808d-11e9-8c4d-ef488bf86578.gif)
**result:** item added and input field is showing the item

**case 2:**

- select an existing item;
- add a new item; 
![combobox-new-item](https://user-images.githubusercontent.com/31067185/58417690-50c04500-808e-11e9-844f-7557a6a74bab.gif)
**result:** item added, input field is empty

Code used
```
public class MainView extends VerticalLayout {

    public MainView() {
        List<String> source =  new ArrayList<>();

        source.add("ABC");
        source.add("DEF");

        ListDataProvider<String> dataProvider = new ListDataProvider<>(source);

        ComboBox<String> comboBox = new ComboBox<>("Issue");
        comboBox.setDataProvider(dataProvider);
        comboBox.setAllowCustomValue(true);

        comboBox.addValueChangeListener(event -> {
            add(new Label("Update value."));
        });

        comboBox.addCustomValueSetListener(event ->{
           if (!dataProvider.getItems().contains(event.getDetail())){
               dataProvider.getItems().add(event.getDetail());
               comboBox.getDataProvider().refreshAll();
               add(new Label("new item added...."));
           }
        });

        add(comboBox);
    }
}
```

**Comment by ZheSun88** [comment]
Also the customer found that `If i add a new value (not in provider too) unfocus, then click the combobox again and delete that value. It doesn't fire a event.`, i guess the same root from the previous behavior.

![ComboBoxIssueCustomValue2](https://user-images.githubusercontent.com/31067185/58418242-f0ca9e00-808f-11e9-88a2-6ab97eb2d93d.gif)

**Comment by pekam** [comment]
I couldn't reproduce the issue.
Is there something missing from the example? It seems that case 2 uses slightly different code. It adds an "update value"-label after the custom value event, indicating that the user calls `setValue` in the `CustomValueSetListener`.

> Also the customer found that If i add a new value (not in provider too) unfocus, then click the combobox again and delete that value. It doesn't fire a event., i guess the same root from the previous behavior.

This is expected behavior. The value is not changed, it's `null`, so no `ValueChangeEvent` should be fired. When clearing the value, no `CustomValueSetEvent` is fired as the user didn't input a custom input string.

The customer should probably call `setValue(e.getDetail())` in the `CustomValueSetListener`. This is the most common use case.

**Comment by ZheSun88** [comment]
You are correct, and I cannot reproduce the issue either. :<
I guess the different behavior comes from using `setDataProvider()` instead of calling `refreshAll()` .
I will close this ticket. 
Thanks.

**Comment by pekam** [comment]
> I guess the different behavior comes from using setDataProvider() instead of calling refreshAll() .

Changing the data provider pretty much resets everything, also setting the value to `null`.
