### ISSUE TITLE
Need a way to introduce an option in the dropdown to clear the combobox

### ISSUE THREAD

**Issue by brp-rasmus** [vaadin/vaadin-combo-box-flow#276]
We have need of a dropdown option (preferablyat the top of the combobox items) that will clear the combox value. This is because our users does not think the "cross" sign in obvious enough. It should also be possible to set a specific label to this "clear" combox option, as it is possible to set labels for combobox items. 

What it would mean then when selecting this option is that it would go back to "null" state, just the same as clicking the cross or deleting the string text in the combox text area.

**Comment by web-padawan** [comment]
> This is because our users does not think the "cross" sign in obvious enough.

That's the public API we have at the moment and use consistently in the components:

- ComboBox
- TextField
- DatePicker
- TimePicker

So, we are not inclined to provide a duplicating API for that (as it would be excessive).

The possible workaround would be to add the item manually, and then use `addValueChangeListener` to check if that item has been clicked and if so, reset the value of the combo-box.

**Comment by brp-rasmus** [comment]
> The possible workaround would be to add the item manually, and then use `addValueChangeListener` to check if that item has been clicked and if so, reset the value of the combo-box.

Yes but if the item value we want to add to the combobox is null (which represents empty state), we cannot display a  label for the item. This is because of the following code in the generateLabel(T item) method in Combobox.java:

`if (item == null) {
            return "";
        }`

**Comment by pekam** [comment]
`null` values are actually not allowed at all in `ComboBox`'s data set. What you can do (what I think @web-padawan meant as well), is create a special object for representing the `null` value, and call `setValue(null)`, when that item is selected by using a value change listener. Then you can also render that item however you want with `setItemLabelGenerator` or `setRenderer`.

The problem with handling this in server-side Java is that this special empty object will be displayed as the selected item for a brief moment before server sends the update to reset the value. So it would be best to handle the selection immediately in client-side. This way the empty object will also not be set as the value in the server-side at any moment.

Here's a full example on how to do this:
```java
@Route("")
public class MainView extends VerticalLayout {

    private static final Person CLEAR_ITEM = new Person();

    public MainView() {
        ComboBox<Person> comboBox = new ComboBox<>();
        add(comboBox);

        // Set the special CLEAR_ITEM as the first item:
        comboBox.setItems(CLEAR_ITEM, new Person("Foo"), new Person("Bar"));

        // Render the CLEAR_ITEM however you want:
        comboBox.setItemLabelGenerator(person -> {
            if (person == CLEAR_ITEM) {
                return "Clear";
            } else {
                return person.getName();
            }
        });

        // Clear value in client-side when selecting the first item:
        comboBox.getElement().executeJs("this.addEventListener('value-changed',"
                + "function(e){if(this.value==='1')this.value='';})");

        // Just to demonstrate that no extra events are fired to server:
        comboBox.addValueChangeListener(e -> add(new Label(
                e.getValue() == null ? "null" : e.getValue().getName())));
    }
}
```
(`Person` is a simple Java bean with a `String` property `name`)

**Comment by pekam** [comment]
^That might require Vaadin 14.0.0.beta2 or newer, as I think it includes a related bug fix for the `<vaadin-combo-box>` web component (for resetting `value` inside `value-changed` listener).

**Comment by web-padawan** [comment]
As I mentioned above in my previous comment https://github.com/vaadin/vaadin-combo-box-flow/issues/276#issuecomment-501260724,

> we are not inclined to provide a duplicating API for that 

The comment above shows how the original request can be achieved.
There hasn't been any activity in this issue since then, so let me close it as won't fix.
