### ISSUE TITLE
Combobox fetches large chunks of data when scrolling very fast

### ISSUE THREAD

**Issue by edler-san** [vaadin/vaadin-combo-box-flow#288]
A customer has a combobox backed by a large dataset - if he scrolls by dragging down the index indicator on the right the fetched data sets quickly grow in size slowing down the application.

In a way this is what I would expect since we are scrolling very, very fast. Now, obviously the backend takes a bit of time to fetch all that, stalling the application. However, the increase in the number of fetched items is probably too steep. A general cap on the number of items might be useful here. This also applies to every other component that fetches from a backend.

To give some perspective: I modified the Bakery application starter (Spring Boot) to create 300000 products and then scrolled through the list. The page sizes observed were 50, 50, 50, 2200, 49800, 163000.

**Comment by TatuLund** [comment]
Is this now fixed by https://github.com/vaadin/vaadin-combo-box/issues/825 ?

**Comment by andytudor** [comment]
> Is this now fixed by [vaadin/vaadin-combo-box#825](https://github.com/vaadin/vaadin-combo-box/issues/825) ?

No, is not fixed
