### ISSUE TITLE
If not setting the item-type for ComboBox, addValueChangeListener causes a compilation error.

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/vaadin-combo-box-flow#3]
@pekam commented on [Thu Sep 28 2017](https://github.com/vaadin/flow/issues/2538)

```
ComboBox comboBox = new ComboBox();
comboBox.addValueChangeListener(event -> {
    System.out.println("value changed");
});
```
Causes:
```
Compilation failure
An unknown compilation problem occurred
```
This happened in a DX testing session, so it will happen for users in the future as well.

Assigning the type parameter for the combobox fixes the issue, but that is hard to tell based on the uninformative error message.

Also Eclipse shows only a yellow warning about using the combobox without the type parameter.

---

@denis-anisimov commented on [Fri Sep 29 2017](https://github.com/vaadin/flow/issues/2538#issuecomment-333031656)

There is no any type parameter in `ComboBox` anymore.
I think the issue is invalid with the current state of Flow.
Please confirm and close it.

---

@pekam commented on [Fri Sep 29 2017](https://github.com/vaadin/flow/issues/2538#issuecomment-333097011)

I double-checked with the latest snapshot and got the same error.
Also the demo at least uses the type parameter: http://flow.app.fi/components/vaadin-combo-box
(`ComboBox<String>` instead of just `ComboBox`)

**Comment by asashour** [comment]
Eclipse and maven give warnings.

I believe the compilation error comes from the compiler settings, which would consider this as an error, but the code per se is ok.

**Comment by denis-anisimov** [comment]
Cannot reproduce it.
No compilation errors.
Only warnings in eclipse.

**Comment by haiwan** [comment]
I'd like to get this ticket reopened. Reasons:
1. It's very easily reproducible, just create a Combobx without any generic parameter and add a value change listener there, then compile the project with `mvn clean package`, you will see the compilation error.
2. When using Vaadin designer, by checking the 'Java' checkbox, it will generate the server side field instance automatically, and the generated field instance of Combobox is untyped.
<img width="318" alt="screen shot 2018-02-28 at 11 55 00" src="https://user-images.githubusercontent.com/3388675/36781332-41b4f6ca-1c7e-11e8-8775-24a14e6431fd.png">

**Comment by haiwan** [comment]
Tried to compile with Java9, got more clear error message
`incompatible types: cannot infer functional interface descriptor for com.vaadin.flow.component.HasValue.ValueChangeListener`
