### ISSUE TITLE
Calling blur() won't close the overlay

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-combo-box-flow#303]
I'd expect that calling `blur()` when the overlay is opened will close it, but this doesn't happen. If this is expected, then there should be a method to close the overlay programmatically.

**Comment by heruan** [comment]
Any feedback about this?

**Comment by tomivirkki** [comment]
Would `comboBox.setOpened(false);` work for this case?

**Comment by pekam** [comment]
If you open the combo-box programmatically by calling `open()` or setting `opened=true`, the overlay won't close with `blur()`, because it doesn't have the focus in this case.

If you click the combo-box to open it, it will have the focus, and calling `blur()` will close it.

**Comment by heruan** [comment]
Thank you @tomivirkki and @pekam, calling `setOpened(false)` works; I was naïvely looking for a `close()` method e didn't spot `setOpened` 😳
