### ISSUE TITLE
Combobox's ValueChangeEvent broken since 3.0.4

### ISSUE THREAD

**Issue by mas4ivv** [vaadin/vaadin-combo-box-flow#305]
Combobox is firing valueChanged events with the wrong value since 3.0.4.

Example code:

```
@Route("")
@PWA(name = "Project Base for Vaadin", shortName = "Project Base")
public class MainView extends VerticalLayout {

    public MainView() {
        ComboBox<String> combo = new ComboBox<>("Combobox", "One", "Two", "Three");
        combo.setValue("Two");
        combo.addValueChangeListener(e -> Notification.show(e.getValue()));
        Button button = new Button("Click me",
                event -> new Dialog(combo).open());
        add(button);
    }
}

```

Steps to reproduce:

- open a dialog by clicking the button
- select "three" in the combobox (there will be a notification showing the selected value)
- click outside the dialog to close it
- open the dialog again -> there will be a notification that "two" is selected

I've traced this down to comboBoxConnector.js:225 - comboBox._selectedKey seems to hold the old value.

**Comment by pekam** [comment]
Thanks for reporting!

Issue verified. It's a regression from #291.

Steps to reproduce without `Dialog`:
1. Set value X from server
2. Select another value Y by user
3. Detach `ComboBox`
4. Attach `ComboBox`
5. Notice that value has changed back to X at the server, while `ComboBox` still displays Y

I've pushed a test case that reproduces the issue to a branch: https://github.com/vaadin/vaadin-combo-box-flow/compare/test-305
