### ISSUE TITLE
Master does not build

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-combo-box-flow#31]
run `mvn clean install`, you get an error because some TB dependency

**Comment by ZheSun88** [comment]
yep, we updated the TB to 6.0.0.alpha1 and there are some changes inside flow, so it will not work via using flow snapshot version. 
PR is coming in https://github.com/vaadin/vaadin-combo-box-flow/pull/33

**Comment by ZheSun88** [comment]
fixed
