### ISSUE TITLE
3.0 SNAPSHOT build fails

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/vaadin-combo-box-flow#317]
Combo Box 3.0-SNAPSHOT build in bender fails due to test failures. See the build history [here](https://bender.vaadin.com/viewType.html?buildTypeId=Flow_ComponentSnapshot_Combobox&tab=buildTypeHistoryList). It looks unstable in a way that every time new tests are failing. It should be investigated and fixed.

**Comment by tomivirkki** [comment]
According to the build history, something broke around 19.12. The build still passes fine if Flow version is fixed to 2.1.0.

**Comment by mehdi-vaadin** [comment]
It passes locally even with Flow 2.2-SNAPSHOT.

**Comment by mehdi-vaadin** [comment]
It was fixed by https://github.com/vaadin/flow/pull/7357.
