### ISSUE TITLE
Could not navigate to 'vaadin-combobox' when running demo

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-combo-box-flow#32]
I followed instructions in README and got that error message in browser

- `mvn clean install`
- `mvn jetty:run`
- `http://localhost:9998/vaadin-combobox`

**Comment by ahie** [comment]
The correct route should be 'vaadin-combo-box' (https://github.com/vaadin/vaadin-combo-box-flow/blob/master/src/test/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java#L33). "Could not navigate to X" comes from the default error view (`com.vaadin.flow.router.RouteNotFoundError`), which is quite confusing.

**Comment by ZheSun88** [comment]
oh, that is an mistake in the readme... the correct one is `Http://localhost:9998/vaadin-combo-box`

**Comment by manolo** [comment]
yep Readme is wrong, Do I PR ?

**Comment by ZheSun88** [comment]
PR has already been there.

**Comment by ZheSun88** [comment]
fixed
