### ISSUE TITLE
setValue bug when called after setItems in ComboBox

### ISSUE THREAD

**Issue by alejandro-du** [vaadin/vaadin-combo-box-flow#333]
If you have this:
```Java
ComboBox<String> comboBox = new ComboBox<>();

add(comboBox, new Button("Select 1", event -> {
    comboBox.setItems("1");
    comboBox.setValue("1");
}));
```
You get this:

![combobox-issue](https://user-images.githubusercontent.com/1708527/47018330-37046a00-d15d-11e8-9ebf-e14374e7fe87.gif)

It should always select "1".

Vaadin 11.0.1 and 10.0.6.

**Comment by mstahv** [comment]
Seems to be fixed in latest LTS and in V17 snapshots.
