### ISSUE TITLE
Combo boxes do not remove or re-use data provider listeners when a data provider is set, causing a memory leak

### ISSUE THREAD

**Issue by eriklumme** [vaadin/vaadin-combo-box-flow#383]
When setting a data provider on a combo box, it calls

    dataProvider.addDataProviderListener(e -> {
        if (e instanceof DataRefreshEvent) {
            dataCommunicator.refresh(((DataRefreshEvent<T>) e).getItem());
        } else {
            refreshAllData(shouldForceServerSideFiltering);
        }
    });

When a new data provider is set, **or if the old data provider is set again**, a new listener will be created. The old listener will be kept in memory, and in cases where the data provider is long-lived, this causes a memory leak.

For example, consider the following code, with a static data provider:

    ComboBox<String> comboBox = new ComboBox<>();
    for(int i = 0; i < 1000; i++) {
        comboBox.setDataProvider(dataProvider);
    }
    System.gc();

As long as the data provider is kept in memory, the heap dump looks something like this

![image](https://user-images.githubusercontent.com/29859656/89530747-b1e9b980-d7f7-11ea-971a-9e4ba4c1f816.png)

An even worse case is when creating many combo boxes with the same data provider, as parts of the combo boxes are kept in memory even when no other references to them remain. It seems impossible to cause a combo box to be garbage collected without any data provider that has been set on it also being garbage collected.

This can be seen by slightly altering the previous example. However, I believe a fix for this issue is difficult, if not impossible.

    for(int i = 0; i < 1000; i++) {
        ComboBox<String> comboBox = new ComboBox<>();
        comboBox.setDataProvider(dataProvider);
    }
    System.gc();

This causes a heap dump as follows:

![image](https://user-images.githubusercontent.com/29859656/89531147-6daae900-d7f8-11ea-95c8-a5a67b095068.png)

**Vaadin version 14.3.2**

**Comment by heruan** [comment]
> An even worse case is when creating many combo boxes with the same data provider, as parts of the combo boxes are kept in memory even when no other references to them remain. It seems impossible to cause a combo box to be garbage collected without any data provider that has been set on it also being garbage collected.
> 
> This can be seen by slightly altering the previous example. However, I believe a fix for this issue is difficult, if not impossible.

@eriklumme This is indeed the exact case for which this issue has been created (see Vaadin Pro Support `#3454`), i.e. data providers are UI-scoped beans shared by many combo boxes and other components with data providers: this lets us have a single data provider to refresh when something changes, and pushing all the updated to every component using that data provider.

Why do you think this could be impossible to fix?

**Comment by eriklumme** [comment]
@heruan Impossible might have been a bad choice of words. My concern is that there is no way for e.g. a combo box to know that it should unregister the data provider listener. The listener is not bound to the attach-detach cycle, so there is no event on a combo box that would inform it that it no longer needs to listen to the data provider.

With this in mind, I can't think of a "correct" solution, but two workarounds:

1. Bind the listener to the attach-detach cycle. The listener would be added on attach, and removed on detach. But what happens then if the data provider is refreshed while the combo box is detached? It could refresh every time it's attached, but that could cause unnecessary overhead.

2. Make it possible to manually unregister the listener. This could either be by setting the data provider to null, or a dedicated method. This would be an extra thing to remember when developing, but would at least make it possible to solve.

**After writing this**, I noticed Tatu's changes. I'll comment my concerns on the PR.

**Comment by heruan** [comment]
Thank @eriklumme, I've also replied to the PR: https://github.com/vaadin/vaadin-combo-box-flow/pull/382#issuecomment-671437795

**Comment by heruan** [comment]
@eriklumme or @TatuLund do you have updates about this? It's been a while and we're still suffering the leak.
