### ISSUE TITLE
ComboBox scroller jumps to a top of dropdown when size is updated with a new estimated value

### ISSUE THREAD

**Issue by mshabarov** [vaadin/vaadin-combo-box-flow#386]
### Description of the issue
I have been implementing a new API in `ComboBox` for fetching items lazily with unknown size (only fetch callback is passed). While testing the implementation, I noticed a unexpected behaviour of `ComboBox` dropdown scroller:
1. When you scroll down by a mouse wheel and reach the bottom border of the scroller, it suddenly jumps to the top of the scrolling, at the beginning of item's list.
2. This only happens when you use a **mouse wheel** AND a **new unknown size lazy loading implementation** in `DataCommunicator`. If you capture the scroller by mouse and move it, OR you use old "defined size" implementation, then it works fine as expected.
3. This sudden jump occurs right after the server-side (`DataCommunicator`) invokes `$connector.updateSize` functions of the combo box's connector. And even before the `$connector.set` is invoked.
4. When this happens, the new estimated size value is passed to `$connector.updateSize`, and it differs from the previous value, because we are in "unknown size" mode and fetch the items chunk by chunk, updating the estimated size each time.
5. This issue is not observed with a `Grid`, although it updates the size pretty much the same.
6. Here is a short demonstration how it looks like:
https://drive.google.com/file/d/1T7CSYwPKTz0RPsYu-nPJiGHXIZk0B5W1/view?usp=sharing

### Minimal reproducible example
1. Checkout the following ComboBox's feature branch https://github.com/vaadin/vaadin-combo-box-flow/tree/355-dataview-impl
2. `mvn clean package -DskipTests`
3. cd `vaadin-combo-box-flow-demo`
4. `mvn clean jetty:run`
5. go to `http://localhost:9998/vaadin-combo-box/lazy-loading`
6.  go to section `Fast Scroll with Custom Item Count Estimate` and open the combo box drop down
7.  scroll the items by mouse wheel to the bottom of the list
8. notice the scroller jump

### Expected behavior
The scroller jumps up by partially, with some offset corresponded to page size.
### Actual behavior
The scroller jumps up to topmost position of the list.
### Versions:
    - Vaadin / Flow version: Vaadin 17.0.0.beta2, Flow 4.0.0
    - Java version: 8
    - OS version: MacOS
    - Browser version (if applicable): Chrome Version 84.0.4147.135, Safari Version 13.0.3
    - Application Server (if applicable): Jetty
    - IDE (if applicable): Intellij IDEA Ultimate 2019.3

**Comment by tomivirkki** [comment]
Whenever the size changes due to user filtering the items, the scroller is expected to jump back to the first item, right. So we need a separate mode for this use-case.
