### ISSUE TITLE
Add custom value to a combobox generates an exception

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/vaadin-combo-box-flow#43]
I expect the combobox with `setAllowCustomValue(true)` will allow to set arbitrary value, but I have:
```java
        ComboBox<String> scoreBox = new ComboBox<>();
        scoreBox.setLabel("Mark a score");
        scoreBox.setAllowCustomValue(true);
        SortedSet<String> items = Arrays.asList("1", "2", "3", "4", "5").stream().collect(Collectors.toCollection(TreeSet::new));
        scoreBox.setItems(items);
        scoreBox.addCustomValueSetListener(e -> {
            items.add(e.getDetail());
            scoreBox.setItems(items);
            scoreBox.setValue(e.getDetail());
        });
```
Setting a custom value (which is not present in items) generates an exception. Both I do it using binder and scoreBox.setValue("8");
`Caused by: java.lang.IllegalArgumentException: The provided value is not part of ComboBox: 8
` 
Small example based on beverage-starter (steps to reproduce are described in commit message):
https://github.com/alexberazouski/beverage-starter-flow/tree/bug/combo-box-set-custom-value

**Comment by MatthiasMak** [comment]
Unfortunately, this bug is still present! When will the fix be implemented?

**Comment by ZheSun88** [comment]
Tested issue with provided code on platform `10.0.2`. The issue cannot be reproduced any more. 
Ticket closed. 
@MatthiasMak if this issue still occurs with your code. please provide a project sample that can reproduce it. Thanks.

**Comment by ajgarciac** [comment]
> 
> 
> @ZheSun88
> 
> **i allow custom value like this:**
> cbCity.setAllowCustomValue( true );
> 
> **Error Log:**
> java.lang.IllegalArgumentException: The provided value is not part of ComboBox: Koln
> at com.vaadin.flow.component.combobox.ComboBox.setValue(ComboBox.java:526)
> at com.vaadin.flow.data.binder.Binder$BindingImpl.initFieldValue(Binder.java:1119)
> at com.vaadin.flow.data.binder.Binder$BindingImpl.access$200(Binder.java:966)
> at com.vaadin.flow.data.binder.Binder$BindingBuilderImpl.bind(Binder.java:780)
> at co.phisoftware.client.ui.AddressFormPanel.bindForm(AddressFormPanel.java:124)
> at co.phisoftware.vaadin.util.PhiCUPanel.(PhiCUPanel.java:43)
> at co.phisoftware.client.ui.AddressFormPanel.(AddressFormPanel.java:39)
> at co.phisoftware.client.ui.order.OrderFormPanel.initForm(OrderFormPanel.java:94)
> at co.phisoftware.vaadin.util.PhiCUPanel.(PhiCUPanel.java:38)
> at co.phisoftware.client.ui.order.OrderFormPanel.(OrderFormPanel.java:38)
> at co.phisoftware.client.ui.order.OrdersPanel.lambda$null$19901ac7$1(OrdersPanel.java:69)
> at com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:133)
> at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:327)
> at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$5ee67f2b$1(ComponentEventBus.java:191)
> at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:379)
> at java.util.ArrayList.forEach(Unknown Source)
> at com.vaadin.flow.internal.nodefeature.ElementListenerMap.fireEvent(ElementListenerMap.java:379)
> at com.vaadin.flow.server.communication.rpc.EventRpcHandler.handleNode(EventRpcHandler.java:59)
> at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:64)
> at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:377)
> at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$0(ServerRpcHandler.java:367)
> at java.util.ArrayList.forEach(Unknown Source)
> at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:367)
> at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:309)
> at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:89)
> at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
> at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1486)
> at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:300)
> at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
> at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
> at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
> at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
> at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
> at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
> at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
> at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
> at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
> at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
> at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
> at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> at java.lang.Thread.run(Unknown Source)

Hi! i have the same problem, have yo solved it,

Thanks

**Comment by ZheSun88** [comment]
Hi @alibozoglu and @ajgarciac , 

It would be better to create a new ticket for the mentioned issue than to comment on a closed one. 
could you provide a sample project that can reproduce this issue in a separated ticket? 

Thanks.

**Comment by DykiSA** [comment]
I am also having this issue with combobox in Vaadin 10.
The issue occur when you enabling the custom value mode then you set the value which is not exists in the provided items.
Does anyone know the workaround?
