### ISSUE TITLE
Setting combobox value fires event asynchronously

### ISSUE THREAD

**Issue by Legioth** [vaadin/vaadin-combo-box-flow#48]
When doing `myComboBox.setValue(someValue)`, any registered value change listener is only notified after the round trip, or never if the component is not attached. This is not what the developer would expect, and it's not consistent with how e.g. `TextField` behaves.

```
ComboBox<String> comboBox = new ComboBox<>("ComboBox", "A", "B");
TextField textField = new TextField("TextField");

Button button = new Button("Change value", e -> {
    comboBox.setValue("A");
    textField.setValue("A");
    System.out.println("Done running the click handler");
});

comboBox.addValueChangeListener(e -> System.out
        .println("ComboBox value changed to " + e.getValue()));
textField.addValueChangeListener(e -> System.out
        .println("TextField value changed to " + e.getValue()));

add(button, comboBox, textField);
```

Expected that `ComboBox value changed to A` is logged before `TextField value changed to A`.
Observed result is that it's logged only after `Done running the click handler`.

Tested using Vaadin platform 10.0.0.alpha17.

**Comment by manolo** [comment]
Unfortunatelly this change has not been released in platform-alpha20 we still need workarounds in Bakery that prevents beta
