### ISSUE TITLE
Refreshing in-memory DataProvider doesn't update ComboBox items

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/vaadin-combo-box-flow#78]
[Note: I'm not sure if this is the same issue as https://github.com/vaadin/vaadin-combo-box-flow/issues/72 since that is talking about lazy dataproviders, so please close if this is a dupe.]

It seems that if a ListDataProvider is refreshed, ComboBox does not notice the changes.

In the following app, clicking the button should update the items in the ComboBox, but nothing happens:
```java
@Route("")
public class MainView extends VerticalLayout {

    List<String> nameList = new ArrayList<>();
    ListDataProvider<String> provider = DataProvider.ofCollection(nameList);

    public MainView() {
        Button update = new Button("Update");
        ComboBox<String> nameSelection = new ComboBox<>("Name");
        nameSelection.setDataProvider(provider);
        add(update, nameSelection);
        update.addClickListener(event -> addNames(nameList, provider));
        setClassName("main-layout");
    }

    private void addNames(List<String> nameList, ListDataProvider<String> provider) {
        nameList.add("John");
        nameList.add("Dave");
        provider.refreshAll();

    }
}
```
In a similar Vaadin 8 application, the ComboBox is updated as expected.

**Comment by OlliTietavainenVaadin** [comment]
If you call `nameSelection.setDataProvider(nameSelection.getDataProvider()); instead of `refreshall`, items are updated correctly.
¯\_(ツ)_/¯

**Comment by pleku** [comment]
This has nothing to do with #72. This is just indeed another bug in the component. It should be quite straight forward to fix and test, but since there is an easy workaround, not prioritizing this issue.

**Comment by KnoxZZ** [comment]
I'm not sure if I'm doing something wrong as I got it working by creating the DataProvider with `DataProvider.of(ArrayList)` instead of `DataProvider.of(List)`.

**Comment by KnoxZZ** [comment]
I actually came to the conclusion that the `ListDataProvider` didn't work when trying to update the whole collection. In my case it was simpler to start using `CallbackDataProvider`.
