### ISSUE TITLE
ComboBox#getValue returns null when field has a pre-selected value

### ISSUE THREAD

**Issue by DiegoCardoso** [vaadin/vaadin-combo-box-flow#85]
This is issue was first raised on Bakery after we started to test latest Flow and components. 

If a value is pre-select from server and user tries to read the value from `ComboBox#getValue`, it returns `null`.

This error is also being raised on https://github.com/vaadin/vaadin-components-testbench/pull/51.

Version affected: 1.0.0rc2

Project with the behavior:
[combo-box-issue.zip](https://github.com/vaadin/vaadin-combo-box-flow/files/2083161/combo-box-issue.zip)

**Comment by FirstWithThisName** [comment]
I still have the problem
